default: &default
  adapter: postgresql
  username: postgres
  password: ''
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: '<%= ENV['POSTGRESQL_USERNAME'] %>'
  password: '<%= ENV['POSTGRESQL_PASSWORD'] %>'
  database: '<%= 'users_notifier_api' %>'
  host: '<%= ENV['POSTGRESQL_HOST'] %>'
  port: '<%= ENV['POSTGRESQL_PORT'] || 5432 %>'

test:
  <<: *default
  username: '<%= ENV['POSTGRESQL_USERNAME'] %>'
  database: db/test_pg

production:
  <<: *default
  database: db/production_pg
